/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wiredtiger.db;

public enum AsyncOpType {
    WT_AOP_NONE(0),
    WT_AOP_COMPACT,
    WT_AOP_INSERT,
    WT_AOP_REMOVE,
    WT_AOP_SEARCH,
    WT_AOP_UPDATE;

    public final int swigValue() {
        return swigValue;
    }

    public static AsyncOpType swigToEnum(int swigValue) {
        AsyncOpType[] swigValues = AsyncOpType.class.getEnumConstants();
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (AsyncOpType swigEnum : swigValues)
            if (swigEnum.swigValue == swigValue)
                return swigEnum;
        throw new IllegalArgumentException("No enum " + AsyncOpType.class + " with value " + swigValue);
    }

    private AsyncOpType() {
        this.swigValue = SwigNext.next++;
    }

    private AsyncOpType(int swigValue) {
        this.swigValue = swigValue;
        SwigNext.next = swigValue + 1;
    }

    private AsyncOpType(AsyncOpType swigEnum) {
        this.swigValue = swigEnum.swigValue;
        SwigNext.next = this.swigValue + 1;
    }

    private final int swigValue;

    private static class SwigNext {
        private static int next = 0;
    }
}
