/*
 * Copyright Lealone Database Group.
 * Licensed under the Server Side Public License, v 1.
 * Initial Developer: zhh
 */
package org.lealone.p2p.gossip;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * A unique version number generator for any state that is generated by the
 * local node.
 */
public class VersionGenerator {
    private static final AtomicInteger version = new AtomicInteger(0);

    public static int getNextVersion() {
        return version.incrementAndGet();
    }
}
