/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lealone.server.protocol;

public enum PacketType {

    // 命令值会包含在协议包中不能随便改动，不同类型的命令值之间有意设置了间隔，用于后续加新命令

    SESSION_INIT(0),
    SESSION_INIT_ACK(1),
    SESSION_CANCEL_STATEMENT(2),
    SESSION_SET_AUTO_COMMIT(3),
    SESSION_CLOSE(4),

    RESULT_FETCH_ROWS(20),
    RESULT_FETCH_ROWS_ACK(20),
    RESULT_CHANGE_ID(21),
    RESULT_RESET(22),
    RESULT_CLOSE(23),

    STATEMENT_QUERY(40),
    STATEMENT_QUERY_ACK(41),
    STATEMENT_UPDATE(42),
    STATEMENT_UPDATE_ACK(43),

    PREPARED_STATEMENT_PREPARE(50),
    PREPARED_STATEMENT_PREPARE_ACK(51),
    PREPARED_STATEMENT_PREPARE_READ_PARAMS(52),
    PREPARED_STATEMENT_PREPARE_READ_PARAMS_ACK(53),
    PREPARED_STATEMENT_QUERY(54),
    PREPARED_STATEMENT_QUERY_ACK(53),
    PREPARED_STATEMENT_UPDATE(56),
    PREPARED_STATEMENT_UPDATE_ACK(57),
    PREPARED_STATEMENT_GET_META_DATA(58),
    PREPARED_STATEMENT_GET_META_DATA_ACK(59),
    PREPARED_STATEMENT_CLOSE(60),

    LOB_READ(71),
    LOB_READ_ACK(72),

    REPLICATION_UPDATE(80),
    REPLICATION_UPDATE_ACK(81),
    REPLICATION_PREPARED_UPDATE(82),
    REPLICATION_PREPARED_UPDATE_ACK(83),
    REPLICATION_COMMIT(84),
    REPLICATION_ROLLBACK(85),
    REPLICATION_CHECK_CONFLICT(86),
    REPLICATION_CHECK_CONFLICT_ACK(87),
    REPLICATION_HANDLE_CONFLICT(88),

    DISTRIBUTED_TRANSACTION_QUERY(100),
    DISTRIBUTED_TRANSACTION_QUERY_ACK(101),
    DISTRIBUTED_TRANSACTION_PREPARED_QUERY(102),
    DISTRIBUTED_TRANSACTION_PREPARED_QUERY_ACK(103),
    DISTRIBUTED_TRANSACTION_UPDATE(104),
    DISTRIBUTED_TRANSACTION_UPDATE_ACK(105),
    DISTRIBUTED_TRANSACTION_PREPARED_UPDATE(106),
    DISTRIBUTED_TRANSACTION_PREPARED_UPDATE_ACK(107),

    DISTRIBUTED_TRANSACTION_COMMIT(120),
    DISTRIBUTED_TRANSACTION_ROLLBACK(121),
    DISTRIBUTED_TRANSACTION_ADD_SAVEPOINT(122),
    DISTRIBUTED_TRANSACTION_ROLLBACK_SAVEPOINT(123),
    DISTRIBUTED_TRANSACTION_VALIDATE(124),
    DISTRIBUTED_TRANSACTION_VALIDATE_ACK(125),

    BATCH_STATEMENT_UPDATE(140),
    BATCH_STATEMENT_UPDATE_ACK(141),
    BATCH_STATEMENT_PREPARED_UPDATE(142), // ACK直接用BATCH_STATEMENT_UPDATE_ACK

    STORAGE_PUT(160),
    STORAGE_PUT_ACK(161),
    STORAGE_APPEND(162),
    STORAGE_APPEND_ACK(163),
    STORAGE_GET(164),
    STORAGE_GET_ACK(165),

    STORAGE_PREPARE_MOVE_LEAF_PAGE(180),
    STORAGE_PREPARE_MOVE_LEAF_PAGE_ACK(181),
    STORAGE_MOVE_LEAF_PAGE(182),
    STORAGE_REMOVE_LEAF_PAGE(183),
    STORAGE_REPLICATE_ROOT_PAGES(184),
    STORAGE_READ_PAGE(185),
    STORAGE_READ_PAGE_ACK(186),

    COMMAND_P2P_MESSAGE(300),
    P2P_ECHO(301),
    P2P_GOSSIP_DIGEST_SYN(302),
    P2P_GOSSIP_DIGEST_ACK(303),
    P2P_GOSSIP_DIGEST_ACK2(304),
    P2P_GOSSIP_SHUTDOWN(305),
    P2P_REQUEST_RESPONSE(306),

    VOID(400),

    STATUS_OK(1000),
    STATUS_CLOSED(1001),
    STATUS_ERROR(1002),
    STATUS_RUN_MODE_CHANGED(1003);

    public final int value;

    private PacketType(int value) {
        this.value = value;
    }
}
